mysql:
  host: 127.0.0.1
  port: 3306
  dbname: order
  username: root
  password:
  charset: utf8
  parseTime: True
  loc: Local
  # 10s
  timeout: 10
  # 设置空闲连接池中的最大连接数。
  max-idle-conns: 10
  # 设置到数据库的最大打开连接数
  max-open-conns: 100
  # 设置连接可重用的最大时间
  conn-max-life-time: 24*3600